version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: netwatch
      POSTGRES_USER: netwatch
      POSTGRES_PASSWORD: netwatch
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn netwatch.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A netwatch worker -l info -c 4
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A netwatch beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis

volumes:
  pgdata:
